### ISSUE TITLE
Generated playlists are empty.

### ISSUE THREAD

**Issue by Reiszecke** [Ardakilic/Recommendify#4] opened 2017-02-18 20:04 UTC
I tried the user as well as the artist option but your stuff seems to be broken. I also tried with another browser and without adblock.

![screen shot 2017-02-18 at 21 02 11](https://cloud.githubusercontent.com/assets/11237541/23096477/8f053e22-f61d-11e6-8b31-a3b71e72a8ae.png)

**Comment by Ardakilic** [comment] 2017-02-18 20:21
Hello,

Thanks for the report. I can confirm the issue.

However it won't be easy to fix as of now.

First of all, I use crossorigin.me to prevent AJAX cors blocking on browsers. Crossorigin + last.fm started to dislike each other, so I cannot fetch data directly.

Secondly, even if I fetch, last.fm started not providing spotify URLs for the songs for public ajax endpoints, so you need to be logged in. The code needs to be refactored, maybe even written from scratch because of this.

I'll dig a bit more and let you know.

**Comment by Reiszecke** [comment] 2017-02-18 20:26
Having to be logged in into both services wouldn't bother me the slightest but this fetching thing is retarded :/ I wish I could help but I am not into web dev at all, good luck bro

**Comment by Ardakilic** [comment] 2017-02-18 20:29
@Reiszecke Thanks, actually even if you're logged in wouldn't solve it, because cookies / sessions cannot be shared across browser tabs, so it won't work even then. I possibly need to "fake login" or need your password / authorization request somehow and fetch amd parse it on server side. That's why I added "help wanted" tag for ideas.

**Comment by Ardakilic** [comment] 2019-05-26 09:47
Late Bump:

There's a work in progress to fetch data from backend. All you need is to provide last.fm credentials, which is connected to a Premium Spotify account.

https://github.com/Ardakilic/Recommendify/tree/next

I'll try to deploy to a service when the work is done.

**Comment by Ardakilic** [comment] 2019-05-27 12:34
Closing in favor of #5 , I've just released a new major version. Currently, I'm looking for a place to deploy the app.

**Closed by Ardakilic** 2019-05-27 12:34 UTC
Labels: bug, help wanted

**Comment by Ardakilic** [comment] 2019-06-01 16:43
I've released v2.0.1 and deployed to a server, you can access to the service at https://recommendify2.herokuapp.com
